### ISSUE TITLE
Linear dimension centred text

### ISSUE THREAD

**Issue by triplus** [hamish2014/FreeCAD_drawing_dimensioning#10]
Inserting linear dimension behaviour could change in a way added text would be centred by default. This after all is what user is after in 99% of the time? Added dimension text can still be moved with Move a dimension's text tool. Default "gap" between dimension line and dimension text could be set in preferences.

**Comment by hamish2014** [comment]
Hi again Triplus,

Thanks for the suggestion.
It is a good one, but i am not going to implement it.
The drawing dimensioning workbench was never not intended to be polished product.
The wb is intended as a temporary work-around until the FreeCAD coders can get round to finishing their version ( a version which will parametric updating, and lots of other exciting stuff).
So i am drawing the line at issues like this.

That said, you are most welcome to fork this github repository and add customize the drawing dimensioning workbench to your needs.

**Comment by triplus** [comment]
I see. I do/did all of this as post-processing in Inkscape until now but your drawing dimensioning workbench allows me to do much less post-processing in Inkscape therefore the time saving is substantial. Thank you for that!

Yes new drawing workbench will for sure be great addition but it could take another year or two to land in FreeCAD in good shape and your drawing dimensioning WB will for sure be used a lot at least by me until then.

Anyway this is how far you are wiling to push drawing dimensioning WB for now and i understand that.

Cheers!
