### ISSUE TITLE
Implement Units - Feature Request 

### ISSUE THREAD

**Issue by quick61** [hamish2014/FreeCAD_drawing_dimensioning#11]
Currently there is only metric values being presented in the dimensioning even when imperial decimal is being used in FreeCAD. With latest update, editing the dimension text is now possible, but is not the most handy solution. (very time consuming having to do all the conversions by hand). 

Also, thanks for the radius! That is a big help!

**Comment by hamish2014** [comment]
Agreed, doing conversions by hand is a huge pain.
The drawing dimensioning workbench now scales values according the unit preference selected in edit->preferences->general->units.

**Comment by quick61** [comment]
This works a treat. Well done!
