### ISSUE TITLE
Error 'module' object has no attribute 'uname'

### ISSUE THREAD

**Issue by BPLRFE** [hamish2014/FreeCAD_drawing_dimensioning#16]
Current Versions displays this message when switching to Dimension Workbench.

> created new document in FreeCAD 015.4415 on Windows 7 64-bit
> placed standard cylinder from part workbench
> created A3-Landscape drawing with standard 3-views
> switched to dimensioning workbench
> error 'module' object has no attribute 'uname' appeared

**Comment by hamish2014** [comment]
interesting, os.uname does not work on a windows system.
patched!
