### ISSUE TITLE
Please add user cblt2l enhancement

### ISSUE THREAD

**Issue by BPLRFE** [hamish2014/FreeCAD_drawing_dimensioning#17]
Please look at his fork (also read his post on the FreeCAD-Developers-Fourm).
His small enhancement makes the quadrants of a circle selectable.
This way a diameter can be added as a linear dimension

**Comment by hamish2014** [comment]
Hi, i did add the enhancement of cblt2l (just at a different spot in the code).
Please check again, you should see the quadrants ...
