### ISSUE TITLE
Support tolerances as upper and lower case text

### ISSUE THREAD

**Issue by BPLRFE** [hamish2014/FreeCAD_drawing_dimensioning#18]
Support tolerances as upper and lower case text.
Would be awesome to have this feature.
Look at he dimension "68" here:
http://de.wikipedia.org/wiki/Technische_Zeichnung#mediaviewer/File:Schneckenwelle.png
or here (1st Variant):
http://www.tzinfo.de/abmasse.html

**Comment by hamish2014** [comment]
Hi, feature added.
