### ISSUE TITLE
Font type

### ISSUE THREAD

**Issue by triplus** [hamish2014/FreeCAD_drawing_dimensioning#20]
Hi.

It would be nice to have font type (font-family) setting in preferences. Leaving the input field blank would work the same as current behaviour. If value would be provided like for example osifont then font-family:osifont would be appended as text style attribute the same as font-size. Add text to drawing should use this setting or have input field available (filled with preferences value).

Cheers!

**Comment by hamish2014** [comment]
support for font families added
