### ISSUE TITLE
Center line scale 

### ISSUE THREAD

**Issue by triplus** [hamish2014/FreeCAD_drawing_dimensioning#22]
Hi.

Currently center line scales (for example when drawing view scale is equal to 5):

```
<g  transform="scale(5.000000,5.000000)" stroke-width="0.250000" >
<path value />
</g>  
```

Produces scaled center line. This behaviour should change by adding additional group like this:

```
<g  transform="scale(5.000000,5.000000)" >
<g   stroke-width="0.05" >
<path value />
</g>
</g> 
```

0.25 divided by 5 = 0,05

Cheers!

**Comment by hamish2014** [comment]
patched
