### ISSUE TITLE
feature request - groove symbols

### ISSUE THREAD

**Issue by microelly2** [hamish2014/FreeCAD_drawing_dimensioning#29]
is it possible to extend the notation indicator  to groove symbols?
http://www.cad-programme.com/tipps/schweisssymbole.html

**Comment by hamish2014** [comment]
Hi microelly2,

I have added all the grove symbols at the link mentioned.
Could you please pull the latest version and tell me what you think.
The grove symbols are scaled according to the font size.

![weldinggrove](https://cloud.githubusercontent.com/assets/7496850/6387563/a9a4f1c2-bd95-11e4-905f-4abd3859c95d.png)

**Comment by hamish2014** [comment]
Correction, i did not add the last symbol on the list.

**Comment by sgrogan** [comment]
Thanks hamish2014 for this!
It works perfectly on kubuntu!
On windows I get "Unhandled unknown exception caught in GUIApplication::notify."
The workbench loads, but without the groove icons in the toolbar.
I tried coping the resources folder to different places, like my macro directory (...\Appdata\roamig\FreeCAD\
With no luck.
Everything was a treat until the last git pull.

**Comment by hamish2014** [comment]
Hi sgrogan,
Just wondering if you have come managed to make progress with your windows issue?

**Comment by sgrogan** [comment]
Hi hamish,To be honest I haven't been able to look seriously. I hope to have time this weekend and I will report anything I find. Thanks for the interest.And again thanks for your efforts. You really have added a lot of functionality with this. If you do a google search on the FreeCAD help forum you will see a lot of frustrations with FreeCAD relieved because of you.Chris-----Original Message-----

**Comment by microelly2** [comment]
Hi hamish,  looks nice,
there seem to be some problems with windows ?!
http://forum.freecadweb.org/viewtopic.php?f=13&t=10044&start=20#p81325

**Comment by sgrogan** [comment]
@hammish
I've made some progress
x64 windows I get the previous error and no welding icons. FreeCAD crashes if I switch to a python wb or any C workbench that has not been previously activated in the same session.
If I remove the comment from line 68 of InitGui.py the crash is fixed and I get the X blank icons for the welding symbols and a warning like
"Cannot find icon: C:\Users\Chris\Desktop\FreeCAD_Portable\Mod\Drawing-Dimensioning\Resources\icons\welding\square_groove.svg"
for all the welding icons, although this is the correct full path. The tooltips work for the icons though.

In x32 windows I get no errors at workbench load, but the same cannot find icon warning. The behavior is the same after cuncommenting the InitGui line. (I do get the drawline icon in both cases and it seems to work)

I haven't checked what  uncommenting this line does on unix.

**Comment by hamish2014** [comment]
@sgrogan , 

Thanks for your help!

The issue appears to do with welding svg icons.
These icons were generated in weldingSymbols.py, without sufficient svg parameters for Windows system.
After adding extra svg headers, everything is now working on my windows 7 x86 boot, using the FreeCAD devoplment built posted on source forge on 15-03-2015.

Please pull the latest version of the drawing dimensioning workbench and let me if know if it works.

Regards,

**Comment by sgrogan** [comment]
I tested x86 and x64 builds on Win7 x64 computer
and x86 build on XP x64 computer (after swapping out numpy see [url]http://forum.freecadweb.org/viewtopic.php?f=10&t=8395&start=60#p77413[url]

All work perfectly! 
I think you can close this. Thanks again for the effort!

**Comment by hamish2014** [comment]
Pleasure @sgrogan , thanks again for help fixing the bug.
