### ISSUE TITLE
Distance Between Parallels 

### ISSUE THREAD

**Issue by quick61** [hamish2014/FreeCAD_drawing_dimensioning#30]
Ran into this today. Needed to dimension the distance between 2 parallel lines of different length that were on an angle. Could not get the proper dimension.

**Comment by quick61** [comment]
![distance](https://cloud.githubusercontent.com/assets/6266769/5942460/c40cd12c-a6e5-11e4-90b3-d2035f273d9c.png)

**Comment by hamish2014** [comment]
Yes it would be possible, you will have to wait a while though;
The list of feature requests for the drawing dimensioning wb has gotten long, and it would not be fair if i jump the queue.

**Comment by quick61** [comment]
No problem. Very much appreciate the effort. Just ran into the limitation working on a question in the FreeCAD help forum and figured it should be mentioned.

**Comment by quick61** [comment]
I was just thinking about this, and maybe just adding a midpoint to lines would work for most all instances. Just a thought for after you get the other request added in. All of them look like they would be most welcome additions.

**Comment by hamish2014** [comment]
Hi quick61, please pull the latest version and check the distance between parallel functionality.
The functionally has been added to the linear dimension command;
select a line, and lines parallel to that will also be selectable ...

![screenshot from 2015-02-18 16 05 43](https://cloud.githubusercontent.com/assets/7496850/6248483/c2a1ba42-b788-11e4-83d0-da405741ff2a.png)

**Comment by quick61** [comment]
Oh yes! Very nice. This is working great. Thank you. I would say this feature request could be considered closed.

**Comment by hamish2014** [comment]
Pleasure, closing issue.
