### ISSUE TITLE
MidPoint Lock for Lines

### ISSUE THREAD

**Issue by catoregon** [hamish2014/FreeCAD_drawing_dimensioning#31]
Hello, I was wondering if there could be a midpoint lock added for lines.

![pic28](https://cloud.githubusercontent.com/assets/11396057/6563297/4d46cac4-c65d-11e4-8f69-893043aaec4a.png)

**Comment by hamish2014** [comment]
Hi catoregon,

please give more detail on what you mean when you say a midpoint lock?

**Comment by catoregon** [comment]
Hey, I just meant if the line on the right side could have a midpoint highlighted as well instead of just the top and bottom. 

When I dimension from the midpoint of the circle to the bottom or top of the line, the angle is a little off and gives the incorrect measurement. 

Thanks!
