### ISSUE TITLE
Drawing Inaccuracy Questions

### ISSUE THREAD

**Issue by catoregon** [hamish2014/FreeCAD_drawing_dimensioning#32]
Hey there,

I was wondering if there was a reason or way to prevent the periodic drawing problems. Not sure if this is programming or user error?

![1](https://cloud.githubusercontent.com/assets/11396057/6566168/e3884cf4-c673-11e4-8fb8-41bf6703352b.png)

![2](https://cloud.githubusercontent.com/assets/11396057/6566175/f5b44c52-c673-11e4-964c-b1af1890efab.png)

**Comment by hamish2014** [comment]
Hi, this looks like it could be a bug with the drawing workbench.
I am going to close the issue on account of it not being related to the drawing dimensioning workbench.
