### ISSUE TITLE
Zoom Feature

### ISSUE THREAD

**Issue by catoregon** [hamish2014/FreeCAD_drawing_dimensioning#33]
It would be awesome if there was a zoom feature that allowed you to magnify areas that are dense and would leave it to show fine details.

**Comment by hamish2014** [comment]
Yes, that would be a very handy feature.
Perhaps the folks responsible for the drawing wb would provide such a feature ...

**Comment by catoregon** [comment]
Yeah that makes sense! I'll post it on the forum.
