### ISSUE TITLE
Error and crash on Windows

### ISSUE THREAD

**Issue by BPLRFE** [hamish2014/FreeCAD_drawing_dimensioning#34]
Hello.

Using 0.15.4651 (uploaded 7 h ago) with Windows 7 - 64 bit.
When activating your workbench I get "unknown C++Exception raised in activateWorkbench".
When trying to change to another workbench, FreeCAD crashes with the well know
"Application does not work anymore" (or similar, I am using german Windows and just translated
the german error message).

**Comment by sgrogan** [comment]
see here: [url]https://github.com/hamish2014/FreeCAD_drawing_dimensioning/issues/29[url]

**Comment by BPLRFE** [comment]
Thanks for mentioning. Seems I did not read far enough ...
