### ISSUE TITLE
Dimension metrics problem

### ISSUE THREAD

**Issue by RobsonW70** [hamish2014/FreeCAD_drawing_dimensioning#36]
Hi,

In the workbench when create dimension on different view (3D) the value/metrics is different for the same edges.
![dimension metrics fault](https://cloud.githubusercontent.com/assets/11805560/6996613/8e15f010-db8a-11e4-8314-60aa0d060167.jpg)

**Comment by hamish2014** [comment]
The drawing dimension workbench measures the distance on the drawing multiplied by the drawing scale, not distances in 3D space.
