### ISSUE TITLE
Dependency on FreeCAD_assembly2

### ISSUE THREAD

**Issue by normandc** [hamish2014/FreeCAD_drawing_dimensioning#39]
Since adding lib3D.py and lineSearches.py symlinks, the Drawing Dimensioning workbench will not load without FreeCAD_assembly2 present. Switching to Drawing dimensioning using the workbench switcher brings the error dialog "No module named lib3D".

Would it be possible to allow the module to load by disabling the functionality provided by the assembly2 module?

The other problem is if the symlink has a hardcoded path to ../FreeCAD_assembly2/lib3D.py. If the end user has renamed the Assembly2 folder, the symlink is broken (yet the drawing dimensioning wb loads normally).

There may also be a problem with Windows users, as symlinks are used on Linux, not on Windows.

**Comment by hamish2014** [comment]
Ok, let me see if i can remove the symlink

**Comment by plaes** [comment]
There's still another issue: `from lineSearches import quadraticLineSearch` where lineSearches is imported from Assembly2

**Comment by hamish2014** [comment]
Thanks, will fix now.
