### ISSUE TITLE
Running python command fails

### ISSUE THREAD

**Issue by herrdeh** [hamish2014/FreeCAD_drawing_dimensioning#41]
I installed everything as given, get the "drawing dimensioning" workbench, can use the "measure distance" tool. But all the commands from the third row of icons fail with a message as to be seen in the screenshot. But I cannot find any new files in the /home/myusername/.FreeCAD/Mod folder.

![dim](https://cloud.githubusercontent.com/assets/7152847/7520592/0febe2e0-f4e8-11e4-9b75-4f58dc4f9324.png)

OS: Ubuntu 14.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.15.4671 (Git)
Branch: releases/FreeCAD-0-15
Hash: 244b3aef360841646cbfe80a1b225c8b39c8380c
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

**Comment by herrdeh** [comment]
OK, found my mistake. A little touch of docu would make things easier!

**Comment by hamish2014** [comment]
Hi Herrdeh, glad you managed to figure it out.
