### ISSUE TITLE
beginners' guide

### ISSUE THREAD

**Issue by herrdeh** [hamish2014/FreeCAD_drawing_dimensioning#42]
Hi,

love the drawing dimensions workbench! - The first tool ever I could do reasonable dimensioning.

But it took me several hours to get into it. I suggest adding something like these lines to make newbies the start a little easier:

First steps:
Open your project and make a fusion out of all its parts. Then go to "drawing" workbench, create a new sheet and place one or several projections of your part with the "orthographic projection" button.

Then change to the "drawing dimension" workbench and start dimensioning.

These videos give you an idea how it works:
https://www.youtube.com/watch?v=CTEPu50bG4U
https://www.youtube.com/watch?v=ztMTLp4wZx4

**Comment by hamish2014** [comment]
Hi Herrdeh,

Thanks for the suggestion.
I have added a help button to the drawing dimensioning workbench, with a link to the videos you mention.
