### ISSUE TITLE
number of digits doesnt follow prefs

### ISSUE THREAD

**Issue by herrdeh** [hamish2014/FreeCAD_drawing_dimensioning#46]
At prefs -> general -> units I set "1 digit after decimal point".
The tool ever provides three digits on my machine.
Bug? - Or should there be a separate control in the tool's prefs for that?

Sorry for flooding you with issues.

**Comment by hamish2014** [comment]
Hi again Herrdeh,

I have marked this issue as an enhancement, maybe one day i will get round to it.

Finally thanks for posting all the issues.
You need to keep in mind, that i created the workbench to assist me with the FreeCAD work i do.
Unfortunately my job does not involve maintaining the drawing dimensioning workbench.
Therefore I do not have the time to give the workbench the polish it deserves ...

**Comment by herrdeh** [comment]
Thank you very much for your work anyway. Only it made FreeCAD really useable for me, because I couldnt deal with the other ways of dimensioning.
