### ISSUE TITLE
Can't use this mod for freeCAD 0.15 win7 installation.

### ISSUE THREAD

**Issue by forproon** [hamish2014/FreeCAD_drawing_dimensioning#48]
I'm new to FreeCAD and Hamish mod. I've followed the instructions to install this mod for windows and I've got the error bellow everytime I wan't to use this mod.

Unknown command 'drawingDimensioning_exportToDxf'
Running the Python command 'dd_circularDimension' failed:
Traceback (most recent call last):
  File "C:\Program Files (x86)\FreeCAD 0.15\Mod\DrawingDimension\circularDimension.py", line 66, in Activated
    V = getDrawingPageGUIVars()
  File "C:\Program Files (x86)\FreeCAD 0.15\Mod\DrawingDimension\dimensioning.py", line 60, in getDrawingPageGUIVars
    raise ValueError, notDrawingPage_title

Current Window not showing a Drawing Page

My FreeCAD and windows info as per below :

OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 32-bit
Version: 0.15.4671 (Git)
Branch: releases/FreeCAD-0-15
Hash: 244b3aef360841646cbfe80a1b225c8b39c8380c
Python version: 2.7.8
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

**Comment by hamish2014** [comment]
Hi, thanks reporting the issue.
I am uploading the patch now.
