### ISSUE TITLE
Running the Pyhton command failed

### ISSUE THREAD

**Issue by mgulbayrak** [hamish2014/FreeCAD_drawing_dimensioning#52]
Hi,

ı tried Freecad with dimensining tool but program always gives same error.

![Phyton error](http://i.hizliresim.com/pg7g0L.png)

 (Windows 8.1 x64 and Windows 7 x64)

**Comment by hamish2014** [comment]
Hi  mgulbayrak, 

The Drawing Dimensioning workbench tools are for page objects generated using the Drawing workbench.
I have added an information window to tell users this.

**Comment by mgulbayrak** [comment]
Sorry , I missed it. 

Thank you.

**Comment by averter** [comment]
Hi,

Either something is wrong with my Freecad build or I have some bug related with this error. 
Basically all of my drawing module commands only appear on the drawing dimensioning module (I don't know if this is normal?
Then whenever I try to add some dimension this error pops up. Even after having created a drawing.
![screenshot from 2016-05-28 08 37 58](https://cloud.githubusercontent.com/assets/16647523/15625944/fb47e110-24af-11e6-837d-07a6285f3d56.png)
Linux Mint 17.3 x64
