### ISSUE TITLE
Dimension edit, no function for tolerance

### ISSUE THREAD

**Issue by fw0stahl** [hamish2014/FreeCAD_drawing_dimensioning#53]
Hello,

i have a problem to edit the whole tolerances on a worksheet. I can't select them. Maybe this failure could help you from the python-console:

could not convert string to float: <text x=Running the Python command 'dd_editText' failed:
Traceback (most recent call last):
  File "/home/mm2/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/textEdit.py", line 95, in Activated
    maskBrush = maskBrush
  File "/home/mm2/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/selectionOverlay.py", line 145, in generateSelectionGraphicsItems
    addSelectionPoint( *element.applyTransforms( float( element.parms['x'] ), float( element.parms['y'] ) ) )

**Comment by hamish2014** [comment]
Hi  fw0stahl,

I have unfortunately been unable to replicate the issue.
Could you please either 
a) post the problem file on http://www.filedropper.com/ so that i can have a look at it, or
b) proved step-by-step instructions to replicate the issue.

**Comment by fw0stahl** [comment]
The document is critical to send it to an other person, sorry. I look if i can reproduce the failure... in the moment new sketches are all right.
