### ISSUE TITLE
French accent in page name make some problems

### ISSUE THREAD

**Issue by Cywil23** [hamish2014/FreeCAD_drawing_dimensioning#59]
Hi,

When I named a page with french accent "é", drawing dimensioning macro didn't work then.

https://framapic.org/ttVGWMCmLzwk/IgiZ12Yx

Error message : 
Running the Python command 'dd_deleteDimension' failed:
Traceback (most recent call last):
  File "C:\Users\crpclb\AppData\Roaming\FreeCAD\Mod\Dimensioning\deleteDimension.py", line 56, in Activated
    V = getDrawingPageGUIVars()
  File "C:\Users\crpclb\AppData\Roaming\FreeCAD\Mod\Dimensioning\dimensioning.py", line 56, in getDrawingPageGUIVars
    pages = App.ActiveDocument.getObjectsByLabel( subWinMW.objectName() )

'ascii' codec can't encode character u'\xe9' in position 9: ordinal not in range(128)

**Comment by hamish2014** [comment]
Ah, unicode:)
Please pull/download the latest version and let me know if your problem is resolved.

**Comment by Cywil23** [comment]
Nice!
It's now ok with the lastest version :)
Thanks
