### ISSUE TITLE
Dimmesions won't show/hide

### ISSUE THREAD

**Issue by EwarStef** [hamish2014/FreeCAD_drawing_dimensioning#70]
Hello.
I'am using an ubuntu version 0.15 of FreeCad. I've just installed the Dimmensioning Workbench and noticed, that dimmensions, that I've created won't show/hide. That's most anoying when I want to reinvent my dimmensioning and I don't know witch one is the dimmension, that I want to delete.

**Comment by hamish2014** [comment]
Hi, 

Users need to press the recompute document button for the visibility change to take affect
