### ISSUE TITLE
Invert scrollwheel zoom behavior?

### ISSUE THREAD

**Issue by horsetailfiddlehead** [hamish2014/FreeCAD_drawing_dimensioning#74]
Is there a way to invert the zoom behavior of the scroll wheel? Scrolling towards me (i.e. as though scrolling farther down a page) causes the window to zoom in, which is opposite to the behavior found in the rest of FreeCAD. Is this a feature within the drawing dimension or in FreeCAD itself?

**Comment by hamish2014** [comment]
Hi, 

The scroll wheel behaviour is controlled in the drawing workbench, which is part of FreeCAD.
In particular refer to 
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Drawing/Gui/DrawingView.cpp#L198
Looking at this code, the behavoir seems to be hard coded.
i.e. cannot be changed via a Edit->Preferences or anything like that.

So your options are
* change the code in question and compile your own version, or
* put in a feature request with the FreeCAD team, or
* get used to the default scroll wheel behaviour

Kind Regards,
