### ISSUE TITLE
Re-licencing to LGPL-2.1

### ISSUE THREAD

**Issue by hamish2014** [hamish2014/FreeCAD_drawing_dimensioning#99]
Hi @yorikvanhavre @SebXcxl @crobarcro @ulikoehler 

When i created the FreeCAD_drawing_dimensioning I choose a licence which is incompatible with FreeCAD's licence.
Therefore I would like to change the licence to the GNU Lesser General Public License, version 2.1
This gives the FreeCAD team to option to use some of the code should they wish to.

As you are all contributors to drawing_dimensioning,  i need your permission to re-licence.
So please respond to this issue with your consent.

Thank you,

**Comment by crobarcro** [comment]
I give permission for my contributions to be released under the GNU Lesser General Public License, version 2.1.

**Comment by SebXcxl** [comment]
I give my permission too for my contributions to be released under the GNU Lesser General Public License, version 2.1.

**Comment by yorikvanhavre** [comment]
I give my permission too for my contributions to be released under the GNU Lesser General Public License, version 2.1. (for assembly2 too if needed)

**Comment by ulikoehler** [comment]
I hereby give permission for my contributions to be released under the GNU Lesser General Public License, version 2.1.

Sorry for taking so long to reply!

**Comment by hamish2014** [comment]
Thanks everyone, much appreciated!
Will re-licence shortly

**Comment by luzpaz** [comment]
@BPLRFE Can this issue now be closed?
